server:
  port: 1010

spring:
  application:
  name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: users
            uri: lb://resource-server
            predicates:
              - Path=/users/**


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  # Eureka Instance Configuration
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true